dbconfig:
  db_type: "postgres"
  host: "127.0.0.1"
  port: "5432"
  config: "sslmode=disable TimeZone=Asia/Shanghai"
  db_name: "wk_db"
  user: "wk_user"
  password: "520@yan"
  max_idle_connections: 10
  max_open_connections: 100
  conn_max_lifetime: "10m"

oauthconfig:
  secret_key: "work_space_auth_oauth_secret_key"
  access_expires_time: "8h"
  refresh_expires_time: "168h"
  issuer: "github.com/jackyuan2022"

redisconfig:
  db: 0
  host: "127.0.0.1:6379"
  password: ""
